### ISSUE TITLE
Qt project: multiple definition of `XXX`

### ISSUE THREAD

**Issue by sonichy** [ginsweater/gif-h#11]
```
error: multiple definition of `GifIMax(int, int)'
error: multiple definition of `GifIMin(int, int)'
error: multiple definition of `GifIAbs(int)'
......
```

**Comment by rversteegen** [comment]
gif.h is a header-only library. It must be included in only one .cpp file.

(Would be nice if you could set a `#define` before including it to get only function declarations, not implementations. I would need that, except I'm using an autogenerated header file for another language anyway.)

**Comment by sonichy** [comment]
Split the gif.h to gif.h(declaration) and gif.cpp(implementation) solved this problem !
```
//gif.h
#ifndef gif_h
#define gif_h
int GifIMax(int l, int r);
......
#endif

//gif.cpp
#include "gif.h"
int GifIMax(int l, int r) { return l>r?l:r; }
......
```
