### ISSUE TITLE
Help required OpenCV Mat provided to GifWriteFrame

### ISSUE THREAD

**Issue by maxpaynestory** [ginsweater/gif-h#14]
Any help would be appreciated. I am trying to convert a video to GIF using OpenCV. Gif output is weird.

Here is the code

```c++

    cv::Mat frame;

    GifWriter writer;

    bool success = video.read(frame);

    GifBegin(&writer, destFile.c_str(), frame.size().width, frame.size().height, 20);

    uint frameCounter = 0;

    while(success && frameCounter<=15){

        success = video.read(frame);

        GifWriteFrame(&writer,frame.data, frame.size().width, frame.size().height, 20);

        frameCounter++;

    }

    GifEnd(&writer);

    video.release();

```

Thanks
![somegif](https://user-images.githubusercontent.com/462460/61695586-3385bb00-ad4d-11e9-8fb8-f3b0b7aa1566.gif)

**Comment by Wohlstand** [comment]
The question: in which color format you streaming your video? You must convert it into RGBA to be accepted by GIFh.

**Comment by Wohlstand** [comment]
I mean, each frame you taking from the video, must be converted into RGBA format, and then, sent to GIF.h.

**Comment by maxpaynestory** [comment]
Thanks, RGBA worked using the below link.

```c++
cv::cvtColor(frame, rgbaFrame, CV_BGR2RGBA);
```
