### ISSUE TITLE
Any change of getting a C99 version of the library?

### ISSUE THREAD

**Issue by raysan5** [ginsweater/gif-h#2]
Hi, I would like to use `gif-h` on [raylib](https://github.com/raysan5/raylib) to add simple .gif export functionality. That would be very useful for students to show and share their small games. Right now raylib offers automatic screenshot generation just pressing F12, some animated image would be great.

I tried it, exporting every 10 frames, and it works ok (maybe a bit slow...) but raylib is C99 and to include `gif-h` it requires to be compiled as C++, it's not a big deal but it should be C99 to be included in the library.

Also, would it be possible to adapt library to header-only style like [STB libraries](https://github.com/nothings/stb), I mean with `GIF_IMPLEMENTATION` define?

**Comment by jarikomppa** [comment]
From a quick glance, converting the code from c++ to c should be relatively simple, mostly about moving the variable declarations to the top of the functions. There's no classes, no templates, etc.

**Comment by raysan5** [comment]
yeah, I see, you're right, it seems that only a couple of tweaks are required... I'll try to give it a go!

**Comment by raysan5** [comment]
ok, just ported the library to C, I also reformatted to single-header similar to STB libraries (sorry, I'm quite picky with formatting, I changed it a bit...). 

In any case, here it is the file: [gif.zip](https://github.com/ginsweater/gif-h/files/1007960/gif.zip)
